# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-12-30 17:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('multi_op', '0001_initial'), ('multi_op', '0002_auto_20200904_1905'), ('multi_op', '0003_auto_20200904_1938')]

    initial = True

    dependencies = [
        ('topologie', '0002_foreign_keys'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultiopOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled_dorm', models.ManyToManyField(blank=True, related_name='enabled_dorm_multiop', to='topologie.Dormitory', verbose_name='enabled dorm')),
            ],
            options={
                'verbose_name': 'dormitories preferences',
            },
        ),
    ]
