# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-09-04 12:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('topologie', '0074_auto_20200419_1640'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preferences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled_dorm', models.ManyToManyField(blank=True, related_name='vlan_tagged', to='topologie.Dormitory', verbose_name='enabled dorm')),
            ],
            options={
                'verbose_name': 'dormitories preferences',
            },
        ),
    ]
