# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-09-04 17:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('multi_op', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Preferences',
            new_name='MultiopOption',
        ),
    ]
