# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-09-04 17:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multi_op', '0002_auto_20200904_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multiopoption',
            name='enabled_dorm',
            field=models.ManyToManyField(blank=True, related_name='enabled_dorm_multiop', to='topologie.Dormitory', verbose_name='enabled dorm'),
        ),
    ]
