# Generated by Django 2.2.18 on 2021-02-08 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0002_foreign_keys'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dname',
            options={'verbose_name': 'DNAME record', 'verbose_name_plural': 'DNAME records'},
        ),
        migrations.AlterModelOptions(
            name='domain',
            options={'permissions': (('change_ttl', 'Can change the TTL of a domain object'),), 'verbose_name': 'domain', 'verbose_name_plural': 'domains'},
        ),
        migrations.AlterModelOptions(
            name='extension',
            options={'permissions': (('use_all_extension', 'Can use all extensions'),), 'verbose_name': 'DNS extension', 'verbose_name_plural': 'DNS extensions'},
        ),
        migrations.AlterModelOptions(
            name='interface',
            options={'permissions': (('change_interface_machine', 'Can change the owner of an interface'),), 'verbose_name': 'interface', 'verbose_name_plural': 'interfaces'},
        ),
        migrations.AlterModelOptions(
            name='iplist',
            options={'verbose_name': 'IPv4 addresses list', 'verbose_name_plural': 'IPv4 addresses lists'},
        ),
        migrations.AlterModelOptions(
            name='iptype',
            options={'permissions': (('use_all_iptype', 'Can use all IP types'),), 'verbose_name': 'IP type', 'verbose_name_plural': 'IP types'},
        ),
        migrations.AlterModelOptions(
            name='ipv6list',
            options={'permissions': (('change_ipv6list_slaac_ip', 'Can change the SLAAC value of an IPv6 addresses list'),), 'verbose_name': 'IPv6 addresses list', 'verbose_name_plural': 'IPv6 addresses lists'},
        ),
        migrations.AlterModelOptions(
            name='machine',
            options={'permissions': (('change_machine_user', 'Can change the user of a machine'),), 'verbose_name': 'machine', 'verbose_name_plural': 'machines'},
        ),
        migrations.AlterModelOptions(
            name='machinetype',
            options={'permissions': (('use_all_machinetype', 'Can use all machine types'),), 'verbose_name': 'machine type', 'verbose_name_plural': 'machine types'},
        ),
        migrations.AlterModelOptions(
            name='mx',
            options={'verbose_name': 'MX record', 'verbose_name_plural': 'MX records'},
        ),
        migrations.AlterModelOptions(
            name='nas',
            options={'verbose_name': 'NAS device', 'verbose_name_plural': 'NAS devices'},
        ),
        migrations.AlterModelOptions(
            name='ns',
            options={'verbose_name': 'NS record', 'verbose_name_plural': 'NS records'},
        ),
        migrations.AlterModelOptions(
            name='ouvertureportlist',
            options={'verbose_name': 'ports opening list', 'verbose_name_plural': 'ports opening lists'},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'verbose_name': 'server role', 'verbose_name_plural': 'server roles'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'service to generate (DHCP, DNS, ...)', 'verbose_name_plural': 'services to generate (DHCP, DNS, ...)'},
        ),
        migrations.AlterModelOptions(
            name='service_link',
            options={'verbose_name': 'link between service and server', 'verbose_name_plural': 'links between service and server'},
        ),
        migrations.AlterModelOptions(
            name='soa',
            options={'verbose_name': 'SOA record', 'verbose_name_plural': 'SOA records'},
        ),
        migrations.AlterModelOptions(
            name='srv',
            options={'verbose_name': 'SRV record', 'verbose_name_plural': 'SRV records'},
        ),
        migrations.AlterModelOptions(
            name='sshfp',
            options={'verbose_name': 'SSHFP record', 'verbose_name_plural': 'SSHFP records'},
        ),
        migrations.AlterModelOptions(
            name='txt',
            options={'verbose_name': 'TXT record', 'verbose_name_plural': 'TXT records'},
        ),
        migrations.AlterModelOptions(
            name='vlan',
            options={'verbose_name': 'VLAN', 'verbose_name_plural': 'VLANs'},
        ),
        migrations.AlterField(
            model_name='domain',
            name='cname',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='related_domain', to='machines.Domain'),
        ),
        migrations.AlterField(
            model_name='iptype',
            name='ouverture_ports',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='machines.OuverturePortList'),
        ),
    ]
