# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-21 01:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("machines", "0042_ns_ns")]

    operations = [
        migrations.RemoveField(model_name="iplist", name="need_infra"),
        migrations.AlterField(
            model_name="iplist",
            name="ip_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="machines.IpType"
            ),
        ),
    ]
