# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-08 01:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0044_auto_20170808_0233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service_link',
            name='asked_regen',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='service_link',
            name='last_regen',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
