# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-08 12:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0045_auto_20170808_0348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='time_regen',
            field=models.DurationField(default=datetime.timedelta(0, 60)),
        ),
    ]
