# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-09 04:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("machines", "0046_auto_20170808_1423")]

    operations = [
        migrations.RemoveField(model_name="service", name="time_regen"),
        migrations.AddField(
            model_name="service",
            name="min_time_regen",
            field=models.DurationField(
                default=datetime.timedelta(0, 60),
                help_text="Temps minimal avant nouvelle génération du service",
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="regular_time_regen",
            field=models.DurationField(
                default=datetime.timedelta(0, 3600),
                help_text="Temps maximal avant nouvelle génération du service",
            ),
        ),
    ]
