# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-25 21:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0048_auto_20170823_2315'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vlan_id', models.IntegerField()),
                ('name', models.CharField(max_length=256)),
                ('comment', models.CharField(max_length=256)),
            ],
        ),
    ]
