# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-25 22:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("machines", "0049_vlan")]

    operations = [
        migrations.AlterField(
            model_name="vlan",
            name="comment",
            field=models.CharField(blank=True, max_length=256),
        )
    ]
