# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-25 23:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0050_auto_20170826_0022'),
    ]

    operations = [
        migrations.AddField(
            model_name='iptype',
            name='vlan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='machines.Vlan'),
        ),
    ]
