# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-28 21:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0051_iptype_vlan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='iptype',
            old_name='domaine_ip',
            new_name='domaine_ip_start',
        ),
        migrations.RemoveField(
            model_name='iptype',
            name='domaine_range',
        ),
        migrations.AddField(
            model_name='iptype',
            name='domaine_ip_stop',
            field=models.GenericIPAddressField(default='255.255.254.254', protocol='IPv4'),
            preserve_default=False,
        ),
    ]
