# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-13 13:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("machines", "0055_nas")]

    operations = [
        migrations.AddField(
            model_name="nas",
            name="port_access_mode",
            field=models.CharField(
                choices=[("802.1X", "802.1X"), ("Mac-address", "Mac-address")],
                default="802.1X",
                max_length=32,
            ),
        )
    ]
