# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-28 15:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0057_nas_autocapture_mac'),
    ]

    operations = [
        migrations.CreateModel(
            name='Port',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin', models.IntegerField()),
                ('end', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PortList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nom de la configuration des ports.', max_length=255)),
                ('interfaces', models.ManyToManyField(to='machines.Interface')),
            ],
        ),
        migrations.AddField(
            model_name='port',
            name='port_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machines.PortList'),
        ),
    ]
