# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-28 16:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0058_auto_20170928_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='port',
            name='protocole',
            field=models.CharField(choices=[('T', 'TCP'), ('U', 'UDP')], default='T', max_length=1),
        ),
    ]
