# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-01 09:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0059_port_protocole'),
    ]

    operations = [
        migrations.AddField(
            model_name='port',
            name='io',
            field=models.CharField(choices=[('I', 'IN'), ('O', 'OUT')], default='O', max_length=1),
        ),
    ]
