# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-01 15:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0060_port_io'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portlist',
            name='interfaces',
        ),
        migrations.AddField(
            model_name='interface',
            name='port_lists',
            field=models.ManyToManyField(to='machines.PortList'),
        ),
    ]
