# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-15 18:33
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0060_iptype_ouverture_ports'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mx',
            name='priority',
            field=models.PositiveIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='ouvertureport',
            name='begin',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(65535)]),
        ),
        migrations.AlterField(
            model_name='ouvertureport',
            name='end',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(65535)]),
        ),
        migrations.AlterField(
            model_name='vlan',
            name='vlan_id',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(4095)]),
        ),
    ]
