# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-15 01:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0063_auto_20171020_0040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='field2',
            field=models.TextField(max_length=2047),
        ),
    ]
