# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-15 14:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("machines", "0064_auto_20171115_0253")]

    operations = [migrations.RenameModel(old_name="Text", new_name="Txt")]
