# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-12-31 20:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("machines", "0070_auto_20171231_1947")]

    operations = [
        migrations.AlterModelOptions(
            name="ns", options={"permissions": (("view_ns", "Peut voir un objet ns"),)}
        )
    ]
