# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-01-08 17:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("machines", "0071_auto_20171231_2100")]

    operations = [
        migrations.AlterModelOptions(
            name="interface",
            options={
                "permissions": (
                    ("view_interface", "Peut voir un objet interface"),
                    (
                        "change_interface_machine",
                        "Peut changer le propriétaire d'une interface",
                    ),
                )
            },
        )
    ]
