# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-01-29 23:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0074_auto_20180129_0352'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ipv6list',
            unique_together=set([]),
        ),
    ]
