# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-01-30 15:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("machines", "0075_auto_20180130_0052")]

    operations = [
        migrations.AlterField(
            model_name="ipv6list",
            name="interface",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ipv6list",
                to="machines.Interface",
            ),
        )
    ]
