# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-03 04:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0079_auto_20180416_0107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ns',
            name='ns',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='machines.Domain'),
        ),
    ]
