# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-05-11 17:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0080_auto_20180502_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service_link',
            name='server',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='machines.Interface'),
        ),
    ]
