# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-06-23 14:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import re2o.mixins


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0083_remove_duplicate_rights'),
    ]

    operations = [
        migrations.CreateModel(
            name='SshFprAlgo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
            options={
                'permissions': (('view_sshfpralgo', 'Can see an SSH fingerprint algorithm'),),
                'verbose_name': 'SSH fingerprint algorithm',
                'verbose_name_plural': 'SSH fingerprint algorithms'
            },
            bases=(re2o.mixins.RevMixin, re2o.mixins.AclMixin, models.Model),
        ),
        migrations.CreateModel(
            name='SshFingerprint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_key_entry', models.TextField(help_text='SSH public key', max_length=2048)),
                ('comment', models.CharField(blank=True, help_text='Comment', max_length=255, null=True)),
                ('algo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='machines.SshFprAlgo')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machines.Machine')),
            ],
            options={
                'permissions': (('view_sshfingerprint', 'Can see an SSH fingerprint'),),
                'verbose_name': 'SSH fingerprint',
                'verbose_name_plural': 'SSH fingerprints'
            },
            bases=(re2o.mixins.RevMixin, re2o.mixins.AclMixin, models.Model),
        ),
    ]
