# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-06-23 14:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import re2o.mixins


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0083_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='SshFingerprint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_entry', models.TextField(max_length=512)),
                ('comment', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'permissions': (('view_sshfingerprint', 'Peut voir un objet sshfingerprint'),),
            },
            bases=(re2o.mixins.RevMixin, re2o.mixins.AclMixin, models.Model),
        ),
        migrations.CreateModel(
            name='SshFprAlgo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=256)),
            ],
            options={
                'permissions': (('view_sshfpralgo', 'Peut voir un algo de chiffrement'),),
            },
            bases=(re2o.mixins.RevMixin, re2o.mixins.AclMixin, models.Model),
        ),
        migrations.AddField(
            model_name='sshfingerprint',
            name='algo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='machines.SshFprAlgo'),
        ),
        migrations.AddField(
            model_name='sshfingerprint',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machines.Machine'),
        ),
    ]
