# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-06-23 16:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0084_auto_20180623_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sshfpralgo',
            name='name',
            field=models.CharField(max_length=256),
        ),
    ]
