# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-06-24 10:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0085_auto_20180623_1817'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sshfingerprint',
            old_name='hash_entry',
            new_name='pub_key_entry',
        ),
        migrations.AlterField(
            model_name='sshfingerprint',
            name='comment',
            field=models.CharField(blank=True, help_text='Commentaire', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sshfingerprint',
            name='pub_key_entry',
            field=models.TextField(help_text='Clef publique ssh', max_length=2048),
        ),
    ]
