# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-06-24 21:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0086_auto_20180624_1254'),
        ('machines', '0082_auto_20180525_2209'),
    ]

    operations = [
    ]
