# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-06-25 14:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import re2o.mixins


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0083_remove_duplicate_rights'),
    ]

    operations = [
        migrations.CreateModel(
            name='DName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=255)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='machines.Extension')),
            ],
            options={
                'permissions': (('view_dname', 'Can see a dname object'),),
                'verbose_name': 'DNAME entry',
                'verbose_name_plural': 'DNAME entries'
            },
            bases=(re2o.mixins.RevMixin, re2o.mixins.AclMixin, models.Model),
        ),
    ]
