# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-06-25 15:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0089_auto_20180625_1700'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extension',
            name='dnssec_reverse_v4',
        ),
        migrations.RemoveField(
            model_name='extension',
            name='dnssec_reverse_v6',
        ),
        migrations.AddField(
            model_name='iptype',
            name='dnssec_reverse_v4',
            field=models.BooleanField(default=False, help_text='Activer DNSSEC sur le reverse DNS IPv4'),
        ),
        migrations.AddField(
            model_name='iptype',
            name='dnssec_reverse_v6',
            field=models.BooleanField(default=False, help_text='Activer DNSSEC sur le reverse DNS IPv6'),
        ),
    ]
