# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-08-06 21:10
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("machines", "0090_auto_20180805_1459")]

    operations = [
        migrations.AddField(
            model_name="iptype",
            name="domaine_ip_netmask",
            field=models.IntegerField(
                default=24,
                help_text="Netmask for the ipv4 range domain",
                validators=[
                    django.core.validators.MaxValueValidator(31),
                    django.core.validators.MinValueValidator(8),
                ],
            ),
        ),
        migrations.AddField(
            model_name="iptype",
            name="domaine_ip_network",
            field=models.GenericIPAddressField(
                blank=True,
                help_text="Network containing the ipv4 range domain ip start/stop. Optional",
                null=True,
                protocol="IPv4",
            ),
        ),
    ]
