# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-07-07 18:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0090_auto_20180625_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='vlan',
            name='arp_protect',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vlan',
            name='dhcp_snooping',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vlan',
            name='dhcpv6_snooping',
            field=models.BooleanField(default=False),
        ),
    ]
