# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-08-07 07:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("machines", "0091_auto_20180806_2310")]

    operations = [
        migrations.RenameField(
            model_name="iptype", old_name="dnssec_reverse_v4", new_name="reverse_v4"
        ),
        migrations.RenameField(
            model_name="iptype", old_name="dnssec_reverse_v6", new_name="reverse_v6"
        ),
    ]
