# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-07-08 18:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0091_auto_20180707_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='vlan',
            name='igmp',
            field=models.BooleanField(default=False, help_text='Gestion multicast v4'),
        ),
        migrations.AddField(
            model_name='vlan',
            name='mld',
            field=models.BooleanField(default=False, help_text='Gestion multicast v6'),
        ),
    ]
