# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-07-10 00:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0092_auto_20180708_2018'),
        ('machines', '0083_remove_duplicate_rights'),
    ]

    operations = [
    ]
