# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-08-07 09:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("machines", "0092_auto_20180807_0926")]

    operations = [
        migrations.AlterField(
            model_name="mx",
            name="name",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="machines.Domain"
            ),
        ),
        migrations.AlterField(
            model_name="mx", name="priority", field=models.PositiveIntegerField()
        ),
    ]
