# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-08-09 14:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0093_auto_20180807_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='txt',
            name='field1',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
