# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-08-11 02:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0094_auto_20180809_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iptype',
            name='reverse_v4',
            field=models.BooleanField(default=False, help_text='Enable reverse DNS for IPv4'),
        ),
        migrations.AlterField(
            model_name='iptype',
            name='reverse_v6',
            field=models.BooleanField(default=False, help_text='Enable reverse DNS for IPv6'),
        ),
    ]
