# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-01-02 23:45
from __future__ import unicode_literals

from django.db import migrations, models


def migrate(apps, schema_editor):
    Role = apps.get_model("machines", "Role")

    for role in Role.objects.filter(specific_role="dns-recursif-server"):
        role.specific_role = "dns-recursive-server"
        role.save()


class Migration(migrations.Migration):

    dependencies = [("machines", "0098_auto_20190102_1745")]

    operations = [migrations.RunPython(migrate)]
