# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-01-02 23:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("machines", "0099_role_recursive_dns")]

    operations = [
        migrations.AlterField(
            model_name="role",
            name="specific_role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("dhcp-server", "DHCP server"),
                    ("switch-conf-server", "Switches configuration server"),
                    ("dns-recursive-server", "Recursive DNS server"),
                    ("ntp-server", "NTP server"),
                    ("radius-server", "RADIUS server"),
                    ("log-server", "Log server"),
                    ("ldap-master-server", "LDAP master server"),
                    ("ldap-backup-server", "LDAP backup server"),
                    ("smtp-server", "SMTP server"),
                    ("postgresql-server", "postgreSQL server"),
                    ("mysql-server", "mySQL server"),
                    ("sql-client", "SQL client"),
                    ("gateway", "Gateway"),
                ],
                max_length=32,
                null=True,
            ),
        )
    ]
