# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-03-03 15:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0101_auto_20190108_1623'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interface',
            old_name='type',
            new_name='machine_type',
        ),
        migrations.RenameField(
            model_name='iptype',
            old_name='type',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='machinetype',
            old_name='type',
            new_name='name',
        ),
    ]
