# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-02 20:22
from __future__ import unicode_literals

from django.db import migrations, models
import machines.models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0102_auto_20190303_1611'),
        ('preferences', '0064_optionalmachine_default_dns_ttl'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='ttl',
            field=models.PositiveIntegerField(default=machines.models.get_default_ttl, verbose_name='Time To Live (TTL)'),
        ),
        migrations.AddField(
            model_name='mx',
            name='ttl',
            field=models.PositiveIntegerField(default=172800, verbose_name='Time To Live (TTL)'),
        ),
        migrations.AddField(
            model_name='ns',
            name='ttl',
            field=models.PositiveIntegerField(default=172800, verbose_name='Time To Live (TTL)'),
        ),
        migrations.AddField(
            model_name='txt',
            name='ttl',
            field=models.PositiveIntegerField(default=172800, verbose_name='Time To Live (TTL)'),
        ),
    ]
