# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-02 20:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0103_auto_20191002_2222'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='domain',
            options={'permissions': (('view_domain', 'Can view a domain object'), ('change_ttl', 'Can change TTL of a domain object')), 'verbose_name': 'domain', 'verbose_name_plural': 'domains'},
        ),
    ]
