# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-02 21:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0104_auto_20191002_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='dname',
            name='ttl',
            field=models.PositiveIntegerField(default=172800, verbose_name='Time To Live (TTL)'),
        ),
    ]
