# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-04 18:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0107_fix_lowercase_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipv6list',
            name='active',
            field=models.BooleanField(default=True, help_text='If false,the DNS will not provide this ip.'),
        ),
    ]
