# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-18 12:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("users", "0048_auto_20170618_0210")]

    operations = [
        migrations.AlterField(
            model_name="serviceuser",
            name="access_group",
            field=models.CharField(
                choices=[
                    ("auth", "auth"),
                    ("readonly", "readonly"),
                    ("usermgmt", "usermgmt"),
                ],
                default="readonly",
                max_length=32,
            ),
        )
    ]
