# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-18 16:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("users", "0049_auto_20170618_1424")]

    operations = [
        migrations.AddField(
            model_name="serviceuser",
            name="comment",
            field=models.CharField(blank=True, help_text="Commentaire", max_length=255),
        )
    ]
