# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-25 02:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("users", "0050_serviceuser_comment")]

    operations = [
        migrations.AddField(
            model_name="user",
            name="telephone",
            field=models.CharField(blank=True, max_length=15, null=True),
        )
    ]
