# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-26 18:51
from __future__ import unicode_literals

from django.db import migrations
import ldapdb.models.fields


class Migration(migrations.Migration):

    dependencies = [("users", "0051_user_telephone")]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name="ldapuser",
                    name="shadowexpire",
                    field=ldapdb.models.fields.CharField(
                        blank=True, db_column="shadowExpire", max_length=200, null=True
                    ),
                )
            ],
            database_operations=[
                migrations.RunSQL(
                    'ALTER TABLE users_ldapuser ADD COLUMN "shadowExpire" varchar(200) NULL;'
                )
            ],
        )
    ]
