# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-26 19:05
from __future__ import unicode_literals

from django.db import migrations
import ldapdb.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0052_ldapuser_shadowexpire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ldapuser',
            name='shadowexpire',
            field=ldapdb.models.fields.IntegerField(blank=True, db_column='shadowExpire', null=True),
        ),
    ]
