# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-26 20:19
from __future__ import unicode_literals

from django.db import migrations
import ldapdb.models.fields


class Migration(migrations.Migration):

    dependencies = [("users", "0053_auto_20170626_2105")]

    operations = [
        migrations.AlterField(
            model_name="ldapuser",
            name="shadowexpire",
            field=ldapdb.models.fields.CharField(
                blank=True, db_column="shadowExpire", max_length=200, null=True
            ),
        )
    ]
