# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-09 20:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0056_2_bantype_pop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ban',
            name='state',
        ),
        migrations.AlterField(
            model_name='ban',
            name='ban_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.BanType'),
        ),
    ]
