# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-09
# Modified by Tudor, with love
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion



class Migration(migrations.Migration):

    dependencies = [
        ('users', '0055_auto_20171003_0556'),
    ]

    operations = [
        migrations.CreateModel(
            name='BanType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(help_text="Description de l'effet et des raisons de la blacklist")),
            ],
        ),
        migrations.AddField(
            model_name='ban',
            name='ban_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.BanType'),
        ),
    ]
