# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-11 20:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0059_iptype_prefix_v6'),
        ('users', '0056_3_bantype_clean'),
    ]

    operations = [
        migrations.AddField(
            model_name='bantype',
            name='inhibited_services',
            field=models.ManyToManyField(to='machines.Service'),
        ),
    ]
