# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-03-07 15:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("users", "0068_auto_20180107_2245")]

    operations = [
        migrations.AddField(
            model_name="club", name="mailing", field=models.BooleanField(default=False)
        )
    ]
