# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-03-24 18:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0069_club_mailing'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listshell',
            options={'permissions': (('view_listshell', "Peut voir un objet shell quelqu'il soit"),)},
        ),
    ]
