# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-04-26 18:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("users", "0071_auto_20180415_1252")]

    operations = [
        migrations.AlterField(
            model_name="ban", name="date_end", field=models.DateTimeField()
        ),
        migrations.AlterField(
            model_name="whitelist", name="date_end", field=models.DateTimeField()
        ),
    ]
