# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-07-15 14:47
from __future__ import unicode_literals

from django.db import migrations, models

def update(apps, schema_editor):
    User = apps.get_model('users', 'User')
    for u in User.objects.all():
        u.verified = True
        u.save()

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0072_auto_20180426_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='verification_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(update)
    ]
