# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-06-29 14:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import re2o.mixins


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0072_auto_20180426_2021'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailAlias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valeur', models.CharField(help_text="username de l'adresse mail", max_length=64, unique=True)),
            ],
            bases=(re2o.mixins.RevMixin, re2o.mixins.AclMixin, models.Model),
        ),
        migrations.RenameField(
            model_name='user',
            old_name='email',
            new_name='external_mail',
        ),
        migrations.AddField(
            model_name='user',
            name='internal_address',
            field=models.BooleanField(default=False, help_text="Activer ou non l'utilisation de l'adresse mail interne"),
        ),
        migrations.AddField(
            model_name='user',
            name='redirection',
            field=models.BooleanField(default=False, help_text='Activer ou non la redirection du mail interne vers le mail externe'),
        ),
        migrations.AddField(
            model_name='mailalias',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Utilisateur associé', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
