# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-06-29 15:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0073_auto_20180629_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailalias',
            name='user',
            field=models.ForeignKey(help_text='Utilisateur associé', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mailalias',
            name='valeur',
            field=models.CharField(help_text="Valeur de l'alias mail", max_length=64, unique=True),
        ),
    ]
