# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-08-15 20:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0074_auto_20180814_1059"),
        ("users", "0074_auto_20180810_2104"),
    ]

    operations = []
