# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-09-08 11:38
from __future__ import unicode_literals

from django.db import migrations
import ldapdb.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0081_auto_20190317_0302'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='ldapserviceuser',
                    name='dn',
                    field=ldapdb.models.fields.CharField(max_length=200, primary_key=True, serialize=False),
                ),
                migrations.AlterField(
                    model_name='ldapserviceusergroup',
                    name='dn',
                    field=ldapdb.models.fields.CharField(max_length=200, primary_key=True, serialize=False),
                ),
                migrations.AlterField(
                    model_name='ldapuser',
                    name='dn',
                    field=ldapdb.models.fields.CharField(max_length=200, primary_key=True, serialize=False),
                ),
                migrations.AlterField(
                    model_name='ldapusergroup',
                    name='dn',
                    field=ldapdb.models.fields.CharField(max_length=200, primary_key=True, serialize=False),
                ),
            ]
        )
    ]
