# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-09-20 12:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0082_auto_20190908_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='shortcuts_enabled',
            field=models.BooleanField(default=True, verbose_name='Enable shortcuts on Re2o website'),
        ),
    ]
