# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-12-21 12:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0084_auto_20191120_0159'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ssh_key',
            field=models.TextField(blank=True, verbose_name='Public ssh key'),
        ),
    ]
