# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-16 18:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0084_auto_20191120_0159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(default='', help_text='External email address allowing us to contact you.', max_length=254),
            preserve_default=False,
        ),
    ]
