# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-04-23 18:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0092_auto_20200423_1804"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ldapuser", old_name="ssh_keys", new_name="sshkeys",
        ),
    ]
