# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-04-23 18:30
from __future__ import unicode_literals

from django.db import migrations
import ldapdb.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0093_auto_20200423_2028"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ldapuser",
            name="sshkeys",
            field=ldapdb.models.fields.ListField(
                blank=True, db_column="sshkeys", max_length=200, null=True
            ),
        ),
    ]
