# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-11-16 18:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0094_remove_user_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='theme',
            field=models.CharField(default='default.css', max_length=255),
        ),
    ]
