# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-08-03 06:54
from __future__ import unicode_literals

from django.db import migrations, models
import printer.models
import printer.validators


class Migration(migrations.Migration):

    dependencies = [
        ('printer', '0002_auto_20180628_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobwithoptions',
            name='file',
            field=models.FileField(upload_to=printer.models.user_printing_path, validators=[printer.validators.FileValidator(allowed_types=['application/pdf'], max_size=26214400)]),
        ),
    ]
