# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-09-07 14:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('printer', '0003_auto_20180803_0854'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobwithoptions',
            name='pages',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='jobwithoptions',
            name='format',
            field=models.CharField(choices=[('A4', 'A4'), ('A3', 'A3')], default='A4', max_length=255),
        ),
        migrations.AlterField(
            model_name='jobwithoptions',
            name='printAs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='print_as_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
