# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-09-08 08:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printer', '0004_auto_20180907_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobwithoptions',
            name='filename',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
