# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-09-08 10:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printer', '0005_jobwithoptions_filename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobwithoptions',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='price'),
        ),
    ]
