# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-09-25 11:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printer', '0006_auto_20180908_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobwithoptions',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Printable', 'Printable'), ('Running', 'Running'), ('Cancelled', 'Cancelled'), ('Finished', 'Finished')], max_length=255),
        ),
    ]
