# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-10-12 10:42
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models
import printer.utils
import printer.validators


class Migration(migrations.Migration):

    dependencies = [
        ('printer', '0007_auto_20180925_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobwithoptions',
            name='file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/var/impressions'), upload_to=printer.models.user_printing_path, validators=[printer.validators.FileValidator(allowed_types=['application/pdf'], max_size=26214400)]),
        ),
    ]
