# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-10-25 10:57
from __future__ import unicode_literals

from django.conf import settings
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion
import printer.utils
import printer.validators
import re2o.mixins


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('printer', '0009_jobwithoptions_paid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Digicode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.BigIntegerField(default=0, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('used_time', models.DateTimeField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            bases=(re2o.mixins.RevMixin, models.Model),
        ),
        migrations.AlterField(
            model_name='jobwithoptions',
            name='file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/var/impressions'), upload_to=printer.models.user_printing_path, validators=[printer.validators.FileValidator(allowed_types=['application/pdf'], max_size=41943040)]),
        ),
    ]
