# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-10-25 23:22
from __future__ import unicode_literals

from django.conf import settings
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion
import printer.models
import printer.validators
import re2o.mixins


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('printer', '0010_auto_20181025_1257'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrintOperation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            bases=(re2o.mixins.RevMixin, re2o.mixins.AclMixin, models.Model),
        ),
        migrations.AlterField(
            model_name='jobwithoptions',
            name='color',
            field=models.CharField(choices=[('Greyscale', 'Greyscale'), ('Color', 'Color')], default='Greyscale', max_length=255, verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='jobwithoptions',
            name='count',
            field=models.PositiveIntegerField(default=1, verbose_name='Count'),
        ),
        migrations.AlterField(
            model_name='jobwithoptions',
            name='disposition',
            field=models.CharField(choices=[('TwoSided', 'Two sided'), ('OneSided', 'One sided'), ('Booklet', 'Booklet')], default='TwoSided', max_length=255, verbose_name='Disposition'),
        ),
        migrations.AlterField(
            model_name='jobwithoptions',
            name='file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/var/impressions'), upload_to=printer.models.user_printing_path, validators=[printer.validators.FileValidator(allowed_types=['application/pdf'], max_size=41943040)], verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='jobwithoptions',
            name='filename',
            field=models.CharField(max_length=255, null=True, verbose_name='File Name'),
        ),
        migrations.AlterField(
            model_name='jobwithoptions',
            name='format',
            field=models.CharField(choices=[('A4', 'A4'), ('A3', 'A3')], default='A4', max_length=255, verbose_name='Format'),
        ),
        migrations.AlterField(
            model_name='jobwithoptions',
            name='perforation',
            field=models.CharField(choices=[('None', 'None'), ('TwoLeftSidedHoles', 'Two left sided holes'), ('TwoRightSidedHoles', 'Two right sided holes'), ('TwoTopHoles', 'Two top holes'), ('TwoBottomHoles', 'Two bottom holes'), ('FourLeftSidedHoles', 'Four left sided holes'), ('FourRightSidedHoles', 'Four right sided holes')], default='None', max_length=255, verbose_name='Perforation'),
        ),
        migrations.AlterField(
            model_name='jobwithoptions',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='jobwithoptions',
            name='printAs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='print_as_user', to=settings.AUTH_USER_MODEL, verbose_name='Print as'),
        ),
        migrations.AlterField(
            model_name='jobwithoptions',
            name='stapling',
            field=models.CharField(choices=[('None', 'None'), ('TopLeft', 'One top left'), ('TopRight', 'One top right'), ('LeftSided', 'Two left sided'), ('RightSided', 'Two right sided')], default='None', max_length=255, verbose_name='Stapling'),
        ),
        migrations.AlterField(
            model_name='jobwithoptions',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Printable', 'Printable'), ('Running', 'Running'), ('Cancelled', 'Cancelled'), ('Finished', 'Finished')], default='Pending', max_length=255, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='jobwithoptions',
            name='print_operation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='printer.PrintOperation'),
            preserve_default=False,
        ),
    ]
