# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-03-20 19:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import preferences.aes_field


class Migration(migrations.Migration):

    replaces = [('preferences', '0001_initial'), ('preferences', '0002_auto_20170625_1923'), ('preferences', '0003_optionaluser_solde_negatif'), ('preferences', '0004_assooption_services'), ('preferences', '0005_auto_20170824_0139'), ('preferences', '0006_auto_20170824_0143'), ('preferences', '0007_auto_20170824_2056'), ('preferences', '0008_auto_20170824_2122'), ('preferences', '0009_assooption_utilisateur_asso'), ('preferences', '0010_auto_20170825_0459'), ('preferences', '0011_auto_20170825_2307'), ('preferences', '0012_generaloption_req_expire_hrs'), ('preferences', '0013_generaloption_site_name'), ('preferences', '0014_generaloption_email_from'), ('preferences', '0015_optionaltopologie_radius_general_policy'), ('preferences', '0016_auto_20170902_1520'), ('preferences', '0017_mailmessageoption'), ('preferences', '0018_optionaltopologie_mac_autocapture'), ('preferences', '0019_remove_optionaltopologie_mac_autocapture'), ('preferences', '0020_optionalmachine_ipv6'), ('preferences', '0021_auto_20171015_1741'), ('preferences', '0022_auto_20171015_1758'), ('preferences', '0023_auto_20171015_2033'), ('preferences', '0024_optionaluser_all_can_create'), ('preferences', '0025_generaloption_general_message'), ('preferences', '0026_auto_20171216_0401'), ('preferences', '0025_auto_20171231_2142'), ('preferences', '0027_merge_20180106_2019'), ('preferences', '0028_auto_20180111_1129'), ('preferences', '0029_auto_20180111_1134'), ('preferences', '0030_auto_20180111_2346'), ('preferences', '0031_optionaluser_self_adhesion'), ('preferences', '0032_optionaluser_min_online_payment'), ('preferences', '0033_generaloption_gtu_sum_up'), ('preferences', '0034_auto_20180114_2025'), ('preferences', '0035_auto_20180114_2132'), ('preferences', '0036_auto_20180114_2141'), ('preferences', '0037_auto_20180114_2156'), ('preferences', '0038_auto_20180114_2209'), ('preferences', '0039_auto_20180115_0003'), ('preferences', '0040_auto_20180129_1745'), ('preferences', '0028_auto_20180128_2203'), ('preferences', '0041_merge_20180130_0052'), ('preferences', '0042_auto_20180222_1743'), ('preferences', '0043_optionalmachine_create_machine'), ('preferences', '0028_assooption_description'), ('preferences', '0029_auto_20180318_1005'), ('preferences', '0029_auto_20180318_0213'), ('preferences', '0030_merge_20180320_1419')]

    initial = True

    dependencies = [
#        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_display_page', models.IntegerField(default=15)),
                ('pagination_large_number', models.IntegerField(default=8)),
                ('pagination_number', models.IntegerField(default=25)),
                ('req_expire_hrs', models.IntegerField(default=48)),
                ('site_name', models.CharField(default='Re2o', max_length=32)),
                ('email_from', models.EmailField(default='www-data@serveur.net', max_length=254)),
                ('general_message', models.TextField(blank=True, default='', help_text='Message général affiché sur le site (maintenance, etc')),
            ],
        ),
        migrations.CreateModel(
            name='OptionalMachine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password_machine', models.BooleanField(default=False)),
                ('max_lambdauser_interfaces', models.IntegerField(default=10)),
                ('max_lambdauser_aliases', models.IntegerField(default=10)),
                ('ipv6', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='OptionalUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_tel_mandatory', models.BooleanField(default=True)),
                ('user_solde', models.BooleanField(default=False)),
                ('gpg_fingerprint', models.BooleanField(default=True)),
                ('solde_negatif', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('all_can_create', models.BooleanField(default=False, help_text="Tous les users peuvent en créer d'autres")),
            ],
        ),
        migrations.CreateModel(
            name='AssoOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Association réseau école machin', max_length=256)),
                ('siret', models.CharField(default='00000000000000', max_length=32)),
                ('contact', models.EmailField(default='contact@example.org', max_length=254)),
                ('telephone', models.CharField(default='0000000000', max_length=15)),
                ('pseudo', models.CharField(default='Asso', max_length=32)),
                ('adresse1', models.CharField(default='1 Rue de exemple', max_length=128)),
                ('adresse2', models.CharField(default='94230 Cachan', max_length=128)),
                ('utilisateur_asso', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('url', models.URLField()),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='logo')),
            ],
        ),
        migrations.CreateModel(
            name='OptionalTopologie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vlan_decision_nok', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='decision_nok', to='machines.Vlan')),
                ('vlan_decision_ok', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='decision_ok', to='machines.Vlan')),
                ('radius_general_policy', models.CharField(choices=[('MACHINE', 'Sur le vlan de la plage ip machine'), ('DEFINED', 'Prédéfini dans "Vlan où placer les machines            après acceptation RADIUS"')], default='DEFINED', max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='MailMessageOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('welcome_mail_fr', models.TextField(default='')),
                ('welcome_mail_en', models.TextField(default='')),
            ],
        ),
        migrations.AlterModelOptions(
            name='assooption',
            options={'permissions': (('view_assooption', "Peut voir les options de l'asso"),)},
        ),
        migrations.AlterModelOptions(
            name='generaloption',
            options={'permissions': (('view_generaloption', 'Peut voir les options générales'),)},
        ),
        migrations.AlterModelOptions(
            name='mailmessageoption',
            options={'permissions': (('view_mailmessageoption', 'Peut voir les options de mail'),)},
        ),
        migrations.AlterModelOptions(
            name='optionalmachine',
            options={'permissions': (('view_optionalmachine', 'Peut voir les options de machine'),)},
        ),
        migrations.AlterModelOptions(
            name='optionaltopologie',
            options={'permissions': (('view_optionaltopologie', 'Peut voir les options de topologie'),)},
        ),
        migrations.AlterModelOptions(
            name='optionaluser',
            options={'permissions': (('view_optionaluser', "Peut voir les options de l'user"),)},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'permissions': (('view_service', 'Peut voir les options de service'),)},
        ),
        migrations.AddField(
            model_name='assooption',
            name='payment',
            field=models.CharField(choices=[('NONE', 'NONE'), ('COMNPAY', 'COMNPAY')], default='NONE', max_length=255),
        ),
        migrations.AddField(
            model_name='optionaluser',
            name='max_solde',
            field=models.DecimalField(decimal_places=2, default=50, max_digits=5),
        ),
        migrations.AddField(
            model_name='optionaluser',
            name='self_adhesion',
            field=models.BooleanField(default=False, help_text='Un nouvel utilisateur peut se créer son compte sur re2o'),
        ),
        migrations.AddField(
            model_name='optionaluser',
            name='min_online_payment',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=5),
        ),
        migrations.AddField(
            model_name='generaloption',
            name='GTU_sum_up',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='generaloption',
            name='GTU',
            field=models.FileField(blank=True, default='', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='assooption',
            name='payment_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='assooption',
            name='payment_pass',
            field=preferences.aes_field.AESEncryptedField(blank=True, max_length=255, null=True),
        ),
        migrations.RemoveField(
            model_name='optionalmachine',
            name='ipv6',
        ),
        migrations.AddField(
            model_name='optionalmachine',
            name='ipv6_mode',
            field=models.CharField(choices=[('SLAAC', 'Autoconfiguration par RA'), ('DHCPV6', 'Attribution des ip par dhcpv6'), ('DISABLED', 'Désactivé')], default='DISABLED', max_length=32),
        ),
        migrations.RemoveField(
            model_name='optionaluser',
            name='all_can_create',
        ),
        migrations.AddField(
            model_name='optionaluser',
            name='all_can_create_adherent',
            field=models.BooleanField(default=False, help_text="Les users peuvent créer d'autres adhérents"),
        ),
        migrations.AddField(
            model_name='optionaluser',
            name='all_can_create_club',
            field=models.BooleanField(default=False, help_text='Les users peuvent créer un club'),
        ),
        migrations.AddField(
            model_name='optionalmachine',
            name='create_machine',
            field=models.BooleanField(default=True, help_text="Permet à l'user de créer une machine"),
        ),
        migrations.AddField(
            model_name='assooption',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
