# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-23 23:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("preferences", "0005_auto_20170824_0139")]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="image",
            field=models.ImageField(blank=True, upload_to="logo"),
        )
    ]
