# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-25 02:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0009_assooption_utilisateur_asso'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptionalTopologie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Vlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vlan_id', models.IntegerField()),
                ('comment', models.CharField(max_length=256)),
            ],
        ),
        migrations.AddField(
            model_name='optionaltopologie',
            name='vlan_decision_nok',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='decision_nok', to='preferences.Vlan'),
        ),
        migrations.AddField(
            model_name='optionaltopologie',
            name='vlan_decision_ok',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='decision_ok', to='preferences.Vlan'),
        ),
    ]
