# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-26 13:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0011_auto_20170825_2307'),
    ]

    operations = [
        migrations.AddField(
            model_name='generaloption',
            name='req_expire_hrs',
            field=models.IntegerField(default=48),
        ),
    ]
