# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-26 13:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("preferences", "0013_generaloption_site_name")]

    operations = [
        migrations.AddField(
            model_name="generaloption",
            name="email_from",
            field=models.EmailField(default="www-data@serveur.net", max_length=254),
        )
    ]
