# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-10 16:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0017_mailmessageoption'),
    ]

    operations = [
        migrations.AddField(
            model_name='optionaltopologie',
            name='mac_autocapture',
            field=models.BooleanField(default=False),
        ),
    ]
