# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-14 16:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0018_optionaltopologie_mac_autocapture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='optionaltopologie',
            name='mac_autocapture',
        ),
    ]
