# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-02 16:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0019_remove_optionaltopologie_mac_autocapture'),
    ]

    operations = [
        migrations.AddField(
            model_name='optionalmachine',
            name='ipv6',
            field=models.BooleanField(default=False),
        ),
    ]
