# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-15 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0020_optionalmachine_ipv6'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optionaltopologie',
            name='radius_general_policy',
            field=models.CharField(choices=[('MACHINE', 'Sur le vlan de la plage ip machine'), ('DEFINED', 'Prédéfini dans "Vlan où placer les machines            après acceptation RADIUS"')], default='DEFINED', max_length=32),
        ),
    ]
