# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-12-16 02:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("preferences", "0024_optionaluser_all_can_create")]

    operations = [
        migrations.AddField(
            model_name="generaloption",
            name="general_message",
            field=models.TextField(
                default="",
                help_text="Message général affiché sur le site (maintenance, etc",
            ),
        )
    ]
