# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-12-16 03:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("preferences", "0025_generaloption_general_message")]

    operations = [
        migrations.AlterField(
            model_name="generaloption",
            name="general_message",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Message général affiché sur le site (maintenance, etc",
            ),
        )
    ]
