# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-01-06 19:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("preferences", "0025_auto_20171231_2142"),
        ("preferences", "0026_auto_20171216_0401"),
    ]

    operations = []
