# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-01-08 14:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0027_merge_20180106_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='assooption',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
