# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-12-16 05:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0027_jauge'),
    ]

    operations = [
        migrations.AddField(
            model_name='jauge',
            name='direction',
            field=models.CharField(choices=[('croissant', 'croissant'), ('decroissant', 'decroissant')], default='croissant', max_length=32),
        ),
    ]
