# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-01-11 10:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("preferences", "0028_auto_20180111_1129")]

    operations = [
        migrations.AddField(
            model_name="assooption",
            name="payment",
            field=models.CharField(
                choices=[("NONE", "NONE"), ("COMNPAY", "COMNPAY")],
                default="NONE",
                max_length=255,
            ),
        )
    ]
