# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-03-20 13:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0029_auto_20180318_1005'),
        ('preferences', '0029_auto_20180318_0213'),
    ]

    operations = [
    ]
