# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-03-23 01:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("preferences", "0030_merge_20180320_1419")]

    operations = [
        migrations.AlterField(
            model_name="generaloption",
            name="email_from",
            field=models.EmailField(default="www-data@example.com", max_length=254),
        )
    ]
