# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-03-24 19:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0070_auto_20180324_1906'),
        ('preferences', '0031_auto_20180323_0218'),
    ]

    operations = [
        migrations.AddField(
            model_name='optionaluser',
            name='shell_default',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.ListShell'),
        ),
    ]
