# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-01-13 16:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("preferences", "0031_optionaluser_self_adhesion")]

    operations = [
        migrations.AddField(
            model_name="optionaluser",
            name="min_online_payment",
            field=models.DecimalField(decimal_places=2, default=10, max_digits=5),
        )
    ]
