# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-04-16 02:35
from __future__ import unicode_literals

from django.db import migrations, models
import re2o.mixins


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0032_optionaluser_shell_default'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccueilOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook_url', models.URLField(blank=True, help_text='Url du compte facebook', null=True)),
                ('twitter_url', models.URLField(blank=True, help_text='Url du compte twitter', null=True)),
                ('twitter_account_name', models.CharField(blank=True, help_text='Nom du compte à afficher', max_length=32, null=True)),
            ],
            options={
                'permissions': (('view_accueiloption', "Peut voir les options de l'accueil"),),
            },
            bases=(re2o.mixins.AclMixin, models.Model),
        ),
    ]
