# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-01-14 19:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0032_optionaluser_min_online_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='generaloption',
            name='GTU_sum_up',
            field=models.TextField(blank=True, default='', help_text='Résumé des CGU'),
        ),
    ]
