# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-04-16 16:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("preferences", "0033_accueiloption")]

    operations = [
        migrations.RenameModel(old_name="AccueilOption", new_name="HomeOption"),
        migrations.AlterModelOptions(
            name="homeoption",
            options={
                "permissions": (
                    ("view_homeoption", "Peut voir les options de l'accueil"),
                )
            },
        ),
    ]
