# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-07-15 14:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0034_auto_20180416_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='optionaluser',
            name='mail_verification',
            field=models.BooleanField(default=True, help_text='Vérification du mail obligatoire'),
        ),
        migrations.AddField(
            model_name='optionaluser',
            name='verification_time',
            field=models.PositiveIntegerField(blank=True, help_text='Durée (en heures) pour vérifier son compte (laisser vide pour ne pas avoir de limite', null=True),
        ),
    ]
