# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-05-05 10:53
from __future__ import unicode_literals

from django.db import migrations, models
import re2o.mixins


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0034_auto_20180416_1120'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.IntegerField(default=7, help_text="Délais entre le mail et la fin d'adhésion", unique=True)),
                ('message', models.CharField(blank=True, default='', max_length=255, null=True)),
            ],
            options={
                'permissions': (('view_reminder', 'Peut voir un objet reminder'),),
            },
            bases=(re2o.mixins.AclMixin, models.Model),
        ),
    ]
