# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-06-26 19:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0034_auto_20180416_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='optionaluser',
            name='mail_extension',
            field=models.CharField(default='@example.org', help_text='Extension principale pour les mails internes', max_length=32),
        ),
    ]
