# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-06-17 15:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("preferences", "0034_auto_20180416_1120")]

    operations = [
        migrations.AddField(
            model_name="optionaluser",
            name="allow_self_subscription",
            field=models.BooleanField(
                default=False,
                help_text="Autoriser les utilisateurs à cotiser par eux mêmes via les moyens de paiement permettant l'auto-cotisation.",
            ),
        )
    ]
