# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-06-29 16:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0035_optionaluser_mail_extension'),
    ]

    operations = [
        migrations.AddField(
            model_name='optionaluser',
            name='mail_accounts',
            field=models.BooleanField(default=False, help_text='Enable mail accounts for users'),
        ),
    ]
