# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-06-30 12:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0036_optionaluser_mail_accounts'),
    ]

    operations = [
        migrations.AddField(
            model_name='optionaluser',
            name='max_mail_alias',
            field=models.IntegerField(default=15, help_text="Max alias mail for a lambda user"),
        ),
    ]
