# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-01-14 21:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0037_auto_20180114_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generaloption',
            name='GTU',
            field=models.FileField(blank=True, default='', null=True, upload_to=''),
        ),
    ]
