# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-07-01 16:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0035_reminder'),
        ('preferences', '0038_mailcontact'),
    ]

    operations = [
    ]
