# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-07-03 05:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0039_merge_20180701_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assooption',
            name='adresse1',
            field=models.CharField(default='1 Rue de exemple', help_text='Adresse', max_length=128),
        ),
        migrations.AlterField(
            model_name='assooption',
            name='contact',
            field=models.EmailField(default='contact@example.org', help_text='Mail de contact', max_length=254),
        ),
        migrations.AlterField(
            model_name='assooption',
            name='description',
            field=models.TextField(blank=True, help_text="Description de l'asso", null=True),
        ),
        migrations.AlterField(
            model_name='assooption',
            name='name',
            field=models.CharField(default='Association réseau école machin', help_text="Nom complet de l'asso", max_length=256),
        ),
        migrations.AlterField(
            model_name='assooption',
            name='payment',
            field=models.CharField(choices=[('NONE', 'NONE'), ('COMNPAY', 'COMNPAY')], default='NONE', help_text='Mode de paiement en ligne', max_length=255),
        ),
        migrations.AlterField(
            model_name='assooption',
            name='payment_id',
            field=models.CharField(blank=True, default='', help_text='Id de paiement en ligne', max_length=255),
        ),
        migrations.AlterField(
            model_name='assooption',
            name='pseudo',
            field=models.CharField(default='Asso', help_text="Pseudo de l'asso", max_length=32),
        ),
        migrations.AlterField(
            model_name='assooption',
            name='siret',
            field=models.CharField(default='00000000000000', help_text='Numero SIRET', max_length=32),
        ),
        migrations.AlterField(
            model_name='assooption',
            name='telephone',
            field=models.CharField(default='0000000000', help_text='Téléphone de contact', max_length=15),
        ),
        migrations.AlterField(
            model_name='assooption',
            name='utilisateur_asso',
            field=models.OneToOneField(blank=True, help_text="Utilisateur dans la db correspondant à l'asso", null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='generaloption',
            name='GTU',
            field=models.FileField(blank=True, default='', help_text="CGU et documents réglementaires à l'inscription", null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='generaloption',
            name='GTU_sum_up',
            field=models.TextField(blank=True, default='', help_text="Résumé des CGU à l'inscription"),
        ),
        migrations.AlterField(
            model_name='generaloption',
            name='email_from',
            field=models.EmailField(default='www-data@example.com', help_text='From des mails envoyés par re2o', max_length=254),
        ),
        migrations.AlterField(
            model_name='generaloption',
            name='general_message',
            field=models.TextField(blank=True, default='', help_text='Message général affiché sur le site (maintenance, etc)'),
        ),
        migrations.AlterField(
            model_name='generaloption',
            name='pagination_large_number',
            field=models.IntegerField(default=8, help_text="Nombre d'item par page paginée, items larges"),
        ),
        migrations.AlterField(
            model_name='generaloption',
            name='pagination_number',
            field=models.IntegerField(default=25, help_text="Nombre d'item par page paginée"),
        ),
        migrations.AlterField(
            model_name='generaloption',
            name='req_expire_hrs',
            field=models.IntegerField(default=48, help_text="Delais d'expiration des token changement de mdp, en heure"),
        ),
        migrations.AlterField(
            model_name='generaloption',
            name='search_display_page',
            field=models.IntegerField(default=15, help_text='Nombre de résultats affichés dans une recherche'),
        ),
        migrations.AlterField(
            model_name='generaloption',
            name='site_name',
            field=models.CharField(default='Re2o', help_text='Nom du site web, par defaut re2o', max_length=32),
        ),
        migrations.AlterField(
            model_name='optionalmachine',
            name='ipv6_mode',
            field=models.CharField(choices=[('SLAAC', 'Autoconfiguration par RA'), ('DHCPV6', 'Attribution des ip par dhcpv6'), ('DISABLED', 'Désactivé')], default='DISABLED', help_text='Mode ipv6', max_length=32),
        ),
        migrations.AlterField(
            model_name='optionalmachine',
            name='max_lambdauser_aliases',
            field=models.IntegerField(default=10, help_text='Maximum de cname pour un user sans droits'),
        ),
        migrations.AlterField(
            model_name='optionalmachine',
            name='max_lambdauser_interfaces',
            field=models.IntegerField(default=10, help_text="Maximum d'interface pour un user sans droits"),
        ),
        migrations.AlterField(
            model_name='optionalmachine',
            name='password_machine',
            field=models.BooleanField(default=False, help_text='Un mot de passe par machine activé'),
        ),
        migrations.AlterField(
            model_name='optionaltopologie',
            name='radius_general_policy',
            field=models.CharField(choices=[('MACHINE', 'Sur le vlan de la plage ip machine'), ('DEFINED', 'Prédéfini dans "Vlan où placer les machines            après acceptation RADIUS"')], default='DEFINED', help_text='Politique par defaut de placement de vlan avec radius', max_length=32),
        ),
        migrations.AlterField(
            model_name='optionaltopologie',
            name='vlan_decision_nok',
            field=models.OneToOneField(blank=True, help_text='Placement par defaut sur ce vlan en cas de rejet', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='decision_nok', to='machines.Vlan'),
        ),
        migrations.AlterField(
            model_name='optionaltopologie',
            name='vlan_decision_ok',
            field=models.OneToOneField(blank=True, help_text="Placement sur ce vlan par default en cas d'accès OK", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='decision_ok', to='machines.Vlan'),
        ),
        migrations.AlterField(
            model_name='optionaluser',
            name='gpg_fingerprint',
            field=models.BooleanField(default=True, help_text='Gpg fingerprint activée'),
        ),
        migrations.AlterField(
            model_name='optionaluser',
            name='is_tel_mandatory',
            field=models.BooleanField(default=True, help_text='Obligation de renseigner le téléphone'),
        ),
        migrations.AlterField(
            model_name='optionaluser',
            name='max_solde',
            field=models.DecimalField(decimal_places=2, default=50, help_text='Valeur maximum du solde', max_digits=5),
        ),
        migrations.AlterField(
            model_name='optionaluser',
            name='min_online_payment',
            field=models.DecimalField(decimal_places=2, default=10, help_text='Montant minimum pour le rechargement online', max_digits=5),
        ),
        migrations.AlterField(
            model_name='optionaluser',
            name='shell_default',
            field=models.OneToOneField(blank=True, help_text='Shell par default', null=True, on_delete=django.db.models.deletion.PROTECT, to='users.ListShell'),
        ),
        migrations.AlterField(
            model_name='optionaluser',
            name='solde_negatif',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Maximum de négatif autorisé', max_digits=5),
        ),
        migrations.AlterField(
            model_name='optionaluser',
            name='user_solde',
            field=models.BooleanField(default=False, help_text='Solde pour les users'),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='message',
            field=models.CharField(blank=True, default='', help_text='Message affiché spécifiquement pour ce rappel', max_length=255, null=True),
        ),
    ]
