# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-01-29 16:45
from __future__ import unicode_literals

from django.db import migrations, models
import preferences.aes_field


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0039_auto_20180115_0003'),
    ]

    operations = [
        migrations.AddField(
            model_name='assooption',
            name='payment_pass',
            field=preferences.aes_field.AESEncryptedField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='assooption',
            name='payment_id',
            field=models.CharField(default='', max_length=255),
        ),
    ]
