# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-01-29 23:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0028_auto_20180128_2203'),
        ('preferences', '0040_auto_20180129_1745'),
    ]

    operations = [
    ]
