# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-07-03 19:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0040_auto_20180703_0743'),
    ]

    operations = [
        migrations.AddField(
            model_name='generaloption',
            name='site_url',
            field=models.CharField(default='re2o.org', help_text='url par défaut du site. par défaut: re2o.org', max_length=32),
        ),
    ]
