# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-07-03 20:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0041_generaloption_site_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generaloption',
            name='site_url',
            field=models.CharField(default='re2o.example.org', help_text='url par défaut du site. par défaut: re2o.example.org', max_length=32),
        ),
    ]
