# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-07-09 17:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0092_auto_20180708_2018'),
        ('preferences', '0042_auto_20180703_2222'),
    ]

    operations = [
        migrations.AddField(
            model_name='optionaltopologie',
            name='switchs_ip_type',
            field=models.OneToOneField(blank=True, help_text="Plage d'ip de management des switchs", null=True, on_delete=django.db.models.deletion.PROTECT, to='machines.IpType'),
        ),
        migrations.AddField(
            model_name='optionaltopologie',
            name='switchs_rest_management',
            field=models.BooleanField(default=False, help_text='Rest management, activé si provision auto'),
        ),
        migrations.AddField(
            model_name='optionaltopologie',
            name='switchs_web_management',
            field=models.BooleanField(default=False, help_text='Web management, activé si provision automatique'),
        ),
    ]
