# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-07-09 20:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0043_auto_20180709_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailmessageoption',
            name='welcome_mail_en',
            field=models.TextField(default='', help_text='Mail de bienvenue en anglais'),
        ),
        migrations.AlterField(
            model_name='mailmessageoption',
            name='welcome_mail_fr',
            field=models.TextField(default='', help_text='Mail de bienvenue en français'),
        ),
    ]
