# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-07-05 13:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0035_optionaluser_allow_self_subscription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assooption',
            name='payment_pass',
        ),
    ]

