# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-07-09 21:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0044_auto_20180709_2237'),
    ]

    operations = [
        migrations.AddField(
            model_name='optionaltopologie',
            name='switchs_web_management_ssl',
            field=models.BooleanField(default=False, help_text='Web management ssl. Assurez-vous que un certif est installé sur le switch !'),
        ),
    ]
