# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-06-30 15:27
from __future__ import unicode_literals

from django.db import migrations, models
import re2o.mixins


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0045_remove_unused_payment_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.EmailField(default='contact@example.org', help_text='Adresse mail de contact', max_length=254)),
                ('commentary', models.CharField(blank=True, help_text="Description de l'utilisation de l'adresse mail associée", max_length=256, null=True)),
            ],
            options={
                'permissions': (('view_mailcontact', 'Peut voir les mails de contact'),),
            },
            bases=(re2o.mixins.AclMixin, models.Model),
        ),
    ]
