# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-07-10 13:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0045_remove_unused_payment_fields'),
        ('preferences', '0045_optionaltopologie_switchs_web_management_ssl'),
    ]

    operations = [
    ]
