# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-07-23 12:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0037_optionaluser_max_mail_alias'),
        ('preferences', '0045_remove_unused_payment_fields'),
    ]

    operations = [
    ]
