# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-07-10 22:15
from __future__ import unicode_literals

from django.db import migrations, models
import re2o.aes_field
import re2o.mixins


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0046_merge_20180710_1533'),
    ]

    operations = [
        migrations.CreateModel(
            name='RadiusKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('radius_key', re2o.aes_field.AESEncryptedField(help_text='Clef radius', max_length=255)),
                ('comment', models.CharField(blank=True, help_text='Commentaire de cette clef', max_length=255, null=True)),
                ('default_switch', models.BooleanField(default=True, help_text='Clef par défaut des switchs', unique=True)),
            ],
            options={
                'permissions': (('view_radiuskey', 'Peut voir un objet radiuskey'),),
            },
            bases=(re2o.mixins.AclMixin, models.Model),
        ),
        migrations.AlterField(
            model_name='optionaluser',
            name='gpg_fingerprint',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='optionaluser',
            name='is_tel_mandatory',
            field=models.BooleanField(default=True),
        ),
    ]
