# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-08-07 13:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0047_mailcontact'),
    ]

    operations = [
        migrations.AddField(
            model_name='optionaluser',
            name='default_home_path',
            field=models.CharField(default='/home/{0}', help_text='Chemin par défaut du home des utilisateurs, formaté avec le pseudo', max_length=256),
        ),
    ]
