# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-08-11 13:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("preferences", "0047_mailcontact")]

    operations = [
        migrations.RenameField(
            model_name="generaloption",
            old_name="general_message",
            new_name="general_message_fr",
        ),
        migrations.AddField(
            model_name="generaloption",
            name="general_message_en",
            field=models.TextField(
                blank=True,
                default="",
                help_text="General message displayed on the English version of the website.",
            ),
        ),
        migrations.AlterField(
            model_name="generaloption",
            name="general_message_fr",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Message général affiché sur le site (maintenance, etc)",
            ),
        ),
    ]
