# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-07-10 23:57
from __future__ import unicode_literals

from django.db import migrations, models
import re2o.aes_field
import re2o.mixins


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0047_auto_20180711_0015'),
    ]

    operations = [
        migrations.CreateModel(
            name='SwitchManagementCred',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('management_id', models.CharField(help_text='Login du switch', max_length=63)),
                ('management_pass', re2o.aes_field.AESEncryptedField(help_text='Mot de passe', max_length=63)),
                ('default_switch', models.BooleanField(default=True, help_text='Creds par défaut des switchs', unique=True)),
            ],
            options={
                'permissions': (('view_switchmanagementcred', 'Peut voir un objet switchmanagementcred'),),
            },
            bases=(re2o.mixins.AclMixin, models.Model),
        ),
    ]
