# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-07-12 15:13
from __future__ import unicode_literals

from django.db import migrations, models
import re2o.aes_field


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0048_switchmanagementcred'),
    ]

    operations = [
        migrations.AddField(
            model_name='optionaltopologie',
            name='sftp_login',
            field=models.CharField(blank=True, help_text='Login sftp des switchs', max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='optionaltopologie',
            name='sftp_pass',
            field=re2o.aes_field.AESEncryptedField(blank=True, help_text='Mot de passe sftp', max_length=63, null=True),
        ),
        migrations.AddField(
            model_name='optionaltopologie',
            name='switchs_provision',
            field=models.CharField(choices=[('sftp', 'sftp'), ('tftp', 'tftp')], default='tftp', help_text='Mode de récupération des confs par les switchs', max_length=32),
        ),
    ]
