# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-08-13 17:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0048_auto_20180811_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='optionaluser',
            name='self_change_shell',
            field=models.BooleanField(default=False, help_text='Users can change their shell'),
        ),
    ]
