# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-08-17 11:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0049_optionaluser_self_change_shell'),
    ]

    operations = [
        migrations.AddField(
            model_name='generaloption',
            name='all_mail_redirect',
            field=models.BooleanField(default=True, help_text='Redirect all sent mail to the choosen address'),
        ),
        migrations.AddField(
            model_name='generaloption',
            name='redirect_address',
            field=models.EmailField(default='no-reply@example.com', help_text='Where to redirect all mails', max_length=254),
        ),
    ]
