# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-08-31 14:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0094_auto_20180815_1918'),
        ('preferences', '0050_auto_20180818_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='optionalmachine',
            name='autocapture_iprange',
            field=models.ManyToManyField(blank=True, help_text="Définit la plage d'ip depuis laquel un utilisateur peut enregistrer une machine filaire", to='machines.IpType'),
        ),
    ]
