# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-10-11 12:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0051_auto_20180919_2225'),
    ]

    operations = [
        migrations.AddField(
            model_name='optionaluser',
            name='delete_notyetactive',
            field=models.IntegerField(default=15, help_text='Inactive users will be deleted after this number of days'),
        ),
    ]
