# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-10-20 10:22
from __future__ import unicode_literals

from django.db import migrations, models
import re2o.mixins


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0051_auto_20180919_2225'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptionalPrinter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('A3_enabled', models.BooleanField(default=False, help_text='Can print in A3 format ?')),
                ('booklet_enabled', models.BooleanField(default=False, help_text='Can print in booklet format ?')),
                ('color_enabled', models.BooleanField(default=False, help_text='Can print in color ?')),
                ('stapling_enabled', models.BooleanField(default=False, help_text='Can use staples ?')),
                ('perforation_enabled', models.BooleanField(default=False, help_text='Can perforate ?')),
                ('max_size', models.IntegerField(default=25, help_text='Maximum size in MB of files to be printed')),
                ('depreciation_coef', models.DecimalField(decimal_places=2, default=0.0, help_text='Set depreciation coefficient', max_digits=5)),
                ('A3_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('A4_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('Color_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('Greyscale_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('Staples_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
            ],
            bases=(re2o.mixins.AclMixin, models.Model),
        ),
    ]
