# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-10-14 22:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0052_optionaluser_delete_notyetactive'),
    ]

    operations = [
        migrations.AddField(
            model_name='optionaluser',
            name='self_change_room',
            field=models.BooleanField(default=False, help_text='Users can edit their room'),
        ),
    ]
