# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-10-25 10:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0053_optionalprinter_printer_enabled'),
        ('preferences', '0053_optionaluser_self_change_room'),
    ]

    operations = [
    ]
