# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-11-14 16:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("preferences", "0053_optionaluser_self_change_room")]

    operations = [
        migrations.AddField(
            model_name="generaloption",
            name="main_site_url",
            field=models.URLField(default="http://re2o.example.org", max_length=255),
        )
    ]
