# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-11-29 21:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0055_generaloption_main_site_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='optionalprinter',
            name='code_duration',
            field=models.DurationField(default=datetime.timedelta(1), help_text='Digicode max duration for printer'),
        ),
    ]
