# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-10-13 14:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import re2o.mixins


class Migration(migrations.Migration):

    dependencies = [
        ("machines", "0095_auto_20180919_2225"),
        ("preferences", "0055_generaloption_main_site_url"),
        ("preferences", "0056_2_radiusoption"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="optionaltopologie", name="radius_general_policy"
        ),
        migrations.RemoveField(
            model_name="optionaltopologie", name="vlan_decision_nok"
        ),
        migrations.RemoveField(model_name="optionaltopologie", name="vlan_decision_ok"),
    ]
