# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-01-03 19:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import re2o.mixins
import preferences.models


def initialize_invoice_template(apps, schema_editor):
    CotisationsOption = apps.get_model('preferences', 'CotisationsOption')
    CotisationsOption.objects.get_or_create()


class Migration(migrations.Migration):

    dependencies = [
        ('cotisations', '0039_documenttemplate'),
        ('preferences', '0058_auto_20190108_1650'),
    ]

    operations = [
        migrations.CreateModel(
            name='CotisationsOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_template', models.OneToOneField(default=preferences.models.default_invoice,on_delete=django.db.models.deletion.PROTECT, related_name='invoice_template', to='cotisations.DocumentTemplate', verbose_name='Template for invoices')),
                ('voucher_template', models.OneToOneField(default=preferences.models.default_voucher, on_delete=django.db.models.deletion.PROTECT, related_name='voucher_template', to='cotisations.DocumentTemplate', verbose_name='Template for subscription voucher')),
            ],
            options={
                'verbose_name': 'cotisations options',
            },
            bases=(re2o.mixins.AclMixin, models.Model),
        ),
        migrations.RunPython(initialize_invoice_template),
    ]
