# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-01-20 18:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0060_assooption_pres_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotisationsoption',
            name='send_voucher_mail',
            field=models.BooleanField(default=False, verbose_name='Send voucher by email when the invoice is controlled.'),
        ),
    ]
