# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-09-20 09:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0062_auto_20190910_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='optionalmachine',
            name='dns_ttl',
            field=models.IntegerField(default=86400, verbose_name='Time To Live for DNS records'),
        ),
    ]
