# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-08 11:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0063_mandate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailmessageoption',
            name='welcome_mail_en',
            field=models.TextField(blank=True, default='', help_text='Welcome email in English'),
        ),
        migrations.AlterField(
            model_name='mailmessageoption',
            name='welcome_mail_fr',
            field=models.TextField(blank=True, default='', help_text='Welcome email in French'),
        ),
    ]
