# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-10 10:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0064_auto_20191008_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='radiuskey',
            name='default_switch',
            field=models.BooleanField(default=False, help_text='Default key for switches'),
        ),
    ]
