# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-02 20:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("preferences", "0065_auto_20191010_1227")]

    operations = [
        migrations.AddField(
            model_name="optionalmachine",
            name="default_dns_ttl",
            field=models.PositiveIntegerField(
                default=172800,
                verbose_name="Default Time To Live (TTL) for CNAME, A and AAA records.",
            ),
        )
    ]
