# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-04-16 17:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0067_auto_20191120_0159'),
    ]

    operations = [
        migrations.AddField(
            model_name='optionaluser',
            name='allow_set_password_during_user_creation',
            field=models.BooleanField(default=False, help_text='If True, users have the choice to receive an email containing a link to reset their password during creation, or to directly set their password in the page. If False, an email is always sent.'),
        ),
    ]
