# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-04-17 00:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0068_optionaluser_allow_set_password_during_user_creation'),
    ]

    operations = [
        migrations.AddField(
            model_name='optionaluser',
            name='disable_emailnotyetconfirmed',
            field=models.IntegerField(default=2, help_text='Users with an email address not yet confirmed will be disabled after this number of days.')
        ),
    ]

