# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-04-15 18:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0068_optionaluser_self_force_move_disabled_user_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optionaluser',
            name='self_force_move_disabled_user_room',
            field=models.BooleanField(default=False, help_text='Users can select a room occupied by a user with a disabled connection.'),
        ),
    ]
