# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-04-23 09:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0070_auto_20200419_0225'),
    ]

    operations = [
        migrations.AddField(
            model_name='optionaluser',
            name='self_change_pseudo',
            field=models.BooleanField(default=True, help_text='Users can edit their pseudo.'),
        ),
    ]
