# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-12-30 15:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cotisations', '0001_model_creation'),
    ]
    

    operations = [
        migrations.AddField(
            model_name='balancepayment',
            name='payment',
            field=models.OneToOneField(default=None, editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='payment_method_balance', to='cotisations.Paiement'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chequepayment',
            name='payment',
            field=models.OneToOneField(default=None, editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='payment_method_cheque', to='cotisations.Paiement'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comnpaypayment',
            name='payment',
            field=models.OneToOneField(default=None, editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='payment_method_comnpay', to='cotisations.Paiement'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='costestimate',
            name='final_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='origin_cost_estimate', to='cotisations.CustomInvoice'),
        ),
        migrations.AddField(
            model_name='cotisation',
            name='vente',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='cotisations.Vente', verbose_name='purchase'),
        ),
        migrations.AddField(
            model_name='facture',
            name='banque',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cotisations.Banque'),
        ),
        migrations.AddField(
            model_name='facture',
            name='paiement',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='cotisations.Paiement'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='facture',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='freepayment',
            name='payment',
            field=models.OneToOneField(default=None, editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='payment_method_free', to='cotisations.Paiement'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notepayment',
            name='payment',
            field=models.OneToOneField(default=None, editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='payment_method_note', to='cotisations.Paiement'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vente',
            name='facture',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cotisations.BaseInvoice', verbose_name='invoice'),
            preserve_default=False,
        ),
    ]
