# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-01-24 10:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cotisations', '0002_foreign_keys'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='baseinvoice',
            options={'permissions': (('view_baseinvoice', 'Can view an base invoice object'),)},
        ),
    ]
