# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-18 21:29
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("cotisations", "0016_auto_20160715_0110")]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="duration",
            field=models.IntegerField(
                blank=True,
                help_text="Durée exprimée en mois entiers",
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
