# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-22 15:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("cotisations", "0017_auto_20170718_2329")]

    operations = [
        migrations.AddField(
            model_name="paiement",
            name="type_paiement",
            field=models.CharField(
                choices=[("check", "Chèque"), (None, "Autre")],
                default=None,
                max_length=255,
            ),
            preserve_default=False,
        )
    ]
