# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-15 18:33
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotisations', '0023_auto_20170902_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='duration',
            field=models.PositiveIntegerField(blank=True, help_text='Durée exprimée en mois entiers', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='vente',
            name='duration',
            field=models.PositiveIntegerField(blank=True, help_text='Durée exprimée en mois entiers', null=True),
        ),
    ]
