# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-27 03:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("cotisations", "0024_auto_20171015_2033")]

    operations = [
        migrations.AddField(
            model_name="article",
            name="type_user",
            field=models.CharField(
                choices=[("Adherent", "Adherent"), ("Club", "Club"), ("All", "All")],
                default="All",
                max_length=255,
            ),
        )
    ]
