# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-06-17 14:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotisations', '0029_auto_20180414_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement',
            name='allow_self_subscription',
            field=models.BooleanField(default=False, verbose_name='Is available for self subscription'),
        ),
    ]
