# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-08-11 23:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("cotisations", "0030_custom_payment")]

    operations = [
        migrations.AddField(
            model_name="comnpaypayment",
            name="production",
            field=models.BooleanField(
                default=True,
                verbose_name="Production mode enabled (production url, instead of homologation)",
            ),
        )
    ]
