# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-06-28 19:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotisations', '0032_chequepayment_comnpaypayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comnpaypayment',
            name='payment_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
