# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-07-03 14:29
from __future__ import unicode_literals

import re2o.aes_field
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotisations', '0033_balancepayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comnpaypayment',
            name='payment_credential',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='ComNpay VAD Number'),
        ),
        migrations.AlterField(
            model_name='comnpaypayment',
            name='payment_pass',
            field=re2o.aes_field.AESEncryptedField(blank=True, max_length=255, null=True, verbose_name='ComNpay Secret Key'),
        ),
    ]
