# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-07-03 15:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotisations', '0034_auto_20180703_0929'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paiement',
            options={'permissions': (('view_paiement', "Can see a payement's details"), ('use', 'Can use a payement')), 'verbose_name': 'Payment method', 'verbose_name_plural': 'Payment methods'},
        ),
        migrations.RemoveField(
            model_name='paiement',
            name='allow_self_subscription',
        ),
        migrations.AddField(
            model_name='paiement',
            name='available_for_everyone',
            field=models.BooleanField(default=False, verbose_name='Is available for every user'),
        ),
    ]
