# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-07-03 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotisations', '0035_auto_20180703_1005'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'permissions': (('view_article', "Can see an article's details"), ('buy_every_article', 'Can buy every_article')), 'verbose_name': 'Article', 'verbose_name_plural': 'Articles'},
        ),
        migrations.RemoveField(
            model_name='article',
            name='allow_self_subscription',
        ),
        migrations.AddField(
            model_name='article',
            name='available_for_everyone',
            field=models.BooleanField(default=False, verbose_name='Is available for every user'),
        ),
    ]
