# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-12-29 21:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("cotisations", "0036_custominvoice_remark")]

    operations = [
        migrations.CreateModel(
            name="CostEstimate",
            fields=[
                (
                    "custominvoice_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="cotisations.CustomInvoice",
                    ),
                ),
                ("validity", models.DurationField(verbose_name="Period of validity")),
                (
                    "final_invoice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="origin_cost_estimate",
                        to="cotisations.CustomInvoice",
                    ),
                ),
            ],
            options={
                "permissions": (
                    ("view_costestimate", "Can view a cost estimate object"),
                )
            },
            bases=("cotisations.custominvoice",),
        )
    ]
