# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-09-30 09:19
from __future__ import unicode_literals

import cotisations.payment_methods.mixins
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("cotisations", "0038_auto_20181231_1657")]

    operations = [
        migrations.CreateModel(
            name="FreePayment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payment",
                    models.OneToOneField(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_method",
                        to="cotisations.Paiement",
                    ),
                ),
            ],
            options={"verbose_name": "Free payment"},
            bases=(cotisations.payment_methods.mixins.PaymentMethodMixin, models.Model),
        )
    ]
