# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-07-04 16:47
from __future__ import unicode_literals

import cotisations.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotisations', '0038_paiement_is_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paiement',
            name='is_balance',
            field=models.BooleanField(default=False, editable=False, help_text='There should be only one balance payment method.', validators=[cotisations.models.check_no_balance], verbose_name='Is user balance'),
        ),
    ]
