# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-03-21 15:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cotisations', '0038_auto_20181231_1657'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chequepayment',
            options={'verbose_name': 'cheque'},
        ),
        migrations.AlterField(
            model_name='balancepayment',
            name='credit_balance_allowed',
            field=models.BooleanField(default=False, verbose_name='allow user to credit their balance'),
        ),
        migrations.AlterField(
            model_name='balancepayment',
            name='maximum_balance',
            field=models.DecimalField(blank=True, decimal_places=2, default=50, help_text='The maximal amount of money allowed for the balance.', max_digits=5, null=True, verbose_name='maximum balance'),
        ),
        migrations.AlterField(
            model_name='balancepayment',
            name='minimum_balance',
            field=models.DecimalField(decimal_places=2, default=0, help_text='The minimal amount of money allowed for the balance at the end of a payment. You can specify negative amount.', max_digits=5, verbose_name='minimum balance'),
        ),
        migrations.AlterField(
            model_name='banque',
            name='name',
            field=models.CharField(max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='baseinvoice',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='comnpaypayment',
            name='minimum_payment',
            field=models.DecimalField(decimal_places=2, default=1, help_text='The minimal amount of money you have to use when paying with ComNpay', max_digits=5, verbose_name='minimum payment'),
        ),
        migrations.AlterField(
            model_name='comnpaypayment',
            name='production',
            field=models.BooleanField(default=True, help_text='When enabled it will use production URL instead of homologation', verbose_name='Production mode'),
        ),
        migrations.AlterField(
            model_name='costestimate',
            name='validity',
            field=models.DurationField(help_text='DD HH:MM:SS', verbose_name='period of validity'),
        ),
        migrations.AlterField(
            model_name='cotisation',
            name='vente',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='cotisations.Vente'),
        ),
        migrations.AlterField(
            model_name='custominvoice',
            name='address',
            field=models.CharField(max_length=255, verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='custominvoice',
            name='paid',
            field=models.BooleanField(default=False, verbose_name='paid'),
        ),
        migrations.AlterField(
            model_name='custominvoice',
            name='payment',
            field=models.CharField(max_length=255, verbose_name='payment type'),
        ),
        migrations.AlterField(
            model_name='custominvoice',
            name='recipient',
            field=models.CharField(max_length=255, verbose_name='recipient'),
        ),
        migrations.AlterField(
            model_name='custominvoice',
            name='remark',
            field=models.TextField(blank=True, null=True, verbose_name='remark'),
        ),
        migrations.AlterField(
            model_name='notepayment',
            name='id_note',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='id of destination note'),
        ),
        migrations.AlterField(
            model_name='notepayment',
            name='port',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='port'),
        ),
    ]
