# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-03-25 07:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cotisations', '0039_auto_20190321_1626'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facture',
            old_name='banque',
            new_name='bank',
        ),
        migrations.RenameField(
            model_name='facture',
            old_name='cheque',
            new_name='cheque_number',
        ),
        migrations.RenameField(
            model_name='facture',
            old_name='control',
            new_name='controlled',
        ),
        migrations.RenameField(
            model_name='facture',
            old_name='valid',
            new_name='validity',
        ),
    ]
