# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-01-20 23:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotisations', '0039_documenttemplate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documenttemplate',
            name='name',
            field=models.CharField(max_length=125, unique=True, verbose_name='name'),
        ),
    ]
