# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-03-25 07:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cotisations', '0040_auto_20190325_0832'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vente',
            old_name='number',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='vente',
            old_name='facture',
            new_name='invoice',
        ),
        migrations.RenameField(
            model_name='vente',
            old_name='prix',
            new_name='price',
        ),
    ]
