# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-03-25 07:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cotisations', '0041_auto_20190325_0837'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cotisation',
            old_name='vente',
            new_name='purchase',
        ),
    ]
