# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-09-20 17:19
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cotisations', '0042_auto_20191120_0159'),
    ]

    operations = [
#        migrations.RemoveField(
#            model_name='article',
#            name='duration',
#        ),
#        migrations.RemoveField(
#            model_name='article',
#            name='duration_days',
#        ),
#        migrations.RemoveField(
#            model_name='article',
#            name='type_cotisation',
#        ),
#        migrations.RemoveField(
#            model_name='cotisation',
#            name='date_end',
#        ),
#        migrations.RemoveField(
#            model_name='cotisation',
#            name='date_start',
#        ),
#        migrations.RemoveField(
#            model_name='cotisation',
#            name='type_cotisation',
#        ),
#        migrations.RemoveField(
#            model_name='vente',
#            name='duration',
#        ),
#        migrations.RemoveField(
#            model_name='vente',
#            name='duration_days',
#        ),
#        migrations.RemoveField(
#            model_name='vente',
#            name='type_cotisation',
#        ),
        migrations.AddField(
            model_name='article',
            name='duration_connection',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='duration of the connection (in months)'),
        ),
        migrations.AddField(
            model_name='article',
            name='duration_days_connection',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='duration of the connection (in days, will be added to duration in months)'),
        ),
        migrations.AddField(
            model_name='article',
            name='duration_days_membership',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='duration of the membership (in days, will be added to duration in months)'),
        ),
        migrations.AddField(
            model_name='article',
            name='duration_membership',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='duration of the membership (in months)'),
        ),
        migrations.AddField(
            model_name='cotisation',
            name='date_end_con',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='end date for the connection'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cotisation',
            name='date_end_memb',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='end date for the membership'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cotisation',
            name='date_start_con',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='start date for the connection'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cotisation',
            name='date_start_memb',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='start date for the membership'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vente',
            name='duration_connection',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='duration of the connection (in months)'),
        ),
        migrations.AddField(
            model_name='vente',
            name='duration_days_connection',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='duration of the connection (in days, will be added to duration in months)'),
        ),
        migrations.AddField(
            model_name='vente',
            name='duration_days_membership',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='duration of the membership (in days, will be added to duration in months)'),
        ),
        migrations.AddField(
            model_name='vente',
            name='duration_membership',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='duration of the membership (in months)'),
        ),
    ]
