# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-09-20 17:19
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cotisations', '0044_separation_membership_connection_p2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='article',
            name='duration_days',
        ),
        migrations.RemoveField(
            model_name='article',
            name='type_cotisation',
        ),
        migrations.RemoveField(
            model_name='cotisation',
            name='date_end',
        ),
        migrations.RemoveField(
            model_name='cotisation',
            name='date_start',
        ),
        migrations.RemoveField(
            model_name='cotisation',
            name='type_cotisation',
        ),
        migrations.RemoveField(
            model_name='vente',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='vente',
            name='duration_days',
        ),
        migrations.RemoveField(
            model_name='vente',
            name='type_cotisation',
        ),
    ]
