# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-09-25 16:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotisations', '0045_separation_membership_connection_p3'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='need_membership',
            field=models.BooleanField(default=True, verbose_name='can be purcharsed without membership'),
        ),
    ]
