# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-11-02 22:05
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotisations', '0048_auto_20201017_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='need_membership',
            field=models.BooleanField(default=True, verbose_name='need membership to be purchased'),
        ),
        migrations.AlterField(
            model_name='vente',
            name='duration_connection',
            field=models.PositiveIntegerField(default=0, verbose_name='duration of the connection (in months)'),
        ),
        migrations.AlterField(
            model_name='vente',
            name='duration_days_connection',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='duration of the connection (in days, will be added to duration in months)'),
        ),
        migrations.AlterField(
            model_name='vente',
            name='duration_days_membership',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='duration of the membership (in days, will be added to duration in months)'),
        ),
        migrations.AlterField(
            model_name='vente',
            name='duration_membership',
            field=models.PositiveIntegerField(default=0, verbose_name='duration of the membership (in months)'),
        ),
    ]
