# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-11-02 22:42
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotisations', '0049_auto_20201102_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='duration_connection',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='duration of the connection (in months)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='duration_days_connection',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='duration of the connection (in days, will be added to duration in months)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='duration_days_membership',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='duration of the membership (in days, will be added to duration in months)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='duration_membership',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='duration of the membership (in months)'),
            preserve_default=False,
        ),
    ]
