# -*- mode: python; coding: utf-8 -*-
"""re2o.contributors
A list of the proud contributors to Re2o
"""

CONTRIBUTORS = [
    'Gabriel Detraz',
    'Hugo Levy-falk',
    'Maël Kervella',
    'Jean-romain Garnier',
    'Arthur Grisel-davy',
    'Laouen Fernet',
    'Augustin Lemesle',
    'Lara Kermarec',
    'Root `root` Root',
    'Alexandre Iooss',
    'Yoann Piétri',
    'Charlie Jacomme',
    'Corentin Canebier',
    'Bombar Maxime',
    'Guillaume Goessel',
    'Matthieu Michelet',
    'Edpibu',
    'Fardale',
    'Jean-marie Mineau',
    'David Sinquin',
    'Gabriel Le Bouder',
    'Simon Brélivet',
    '~anonymised~',
    'Leïla Bekaddour',
    'Éloi Alain',
    'Benjamin Graillot',
    'Pierre Cadart',
    'Antoine Vintache',
    'Thibault De Boutray',
    'Delphine Salvy',
    'Joanne Steiner',
    'Krokmou',
    'B',
    'Daniel Stan',
    'Gwenael Le Hir',
    'Hugo Hervieux',
    'Mikachu',
    'Nymous',
    'Pierre-antoine Comby',
    'Vincent Le Gallic',
    'Esum',
]