# -*- mode: python; coding: utf-8 -*-
"""re2o.contributors
A list of the proud contributors to Re2o
"""

CONTRIBUTORS = [
    "Gabriel 'chibrac' Detraz",
    "Hugo 'klafyvel' Levy-Falk",
    "Maël 'MoaMoaK' Kervella",
    "Arthur 'Grizzly' Grisel-Davy",
    "Augustin 'Dalahro' Lemesle",
    "Laouen 'volgarr' Fernet",
    "Lara 'lhark' Kermarec",
    "Alexandre 'erdnaxe' Ioss",
    "Charlie Jacomme",
    "Root 'root' Root",
    "Yoann 'nanoy' Pietri",
    "Maxime Bombar",
    "Matthieu 'lebanni' Michelet",
    "Guillaume 'guimoz' Goessel",
    "edpibu",
    "Jean-Romain 'lerennais' Garnier",
    "David '5-1' Sinquin",
    "Gabriel Le Bouder",
    "Fardale",
    "Éloi Alain",
    "Simon Brelivet",
    "Antoine Vintache",
    "Benjamin Graillot",
    "Thibault 'tipunchetrhum' Deboutray",
    "Joanne Steiner",
    "Delphine Salvy",
    "Pierre Cadart",
    "'Krokmou'",
    "Vincent Le Gallic",
    "Hugo 'shaka' Hervieux",
    "Pierre-Antoine Comby",
    "Nymous",
    "Mikachu",
    "Baptiste 'B' Fournier",
    "Gwenael Le Hir",
    "Daniel Stan",
]
