# Generated by Django 2.2.18 on 2021-02-08 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('topologie', '0002_foreign_keys'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accesspoint',
            options={'verbose_name': 'access point', 'verbose_name_plural': 'access points'},
        ),
        migrations.AlterModelOptions(
            name='building',
            options={'verbose_name': 'building', 'verbose_name_plural': 'buildings'},
        ),
        migrations.AlterModelOptions(
            name='constructorswitch',
            options={'verbose_name': 'switch constructor', 'verbose_name_plural': 'switch constructors'},
        ),
        migrations.AlterModelOptions(
            name='dormitory',
            options={'verbose_name': 'dormitory', 'verbose_name_plural': 'dormitories'},
        ),
        migrations.AlterModelOptions(
            name='modelswitch',
            options={'verbose_name': 'switch model', 'verbose_name_plural': 'switch models'},
        ),
        migrations.AlterModelOptions(
            name='moduleonswitch',
            options={'verbose_name': 'link between switch and module', 'verbose_name_plural': 'links between switch and module'},
        ),
        migrations.AlterModelOptions(
            name='moduleswitch',
            options={'verbose_name': 'switch module', 'verbose_name_plural': 'switch modules'},
        ),
        migrations.AlterModelOptions(
            name='port',
            options={'verbose_name': 'port', 'verbose_name_plural': 'ports'},
        ),
        migrations.AlterModelOptions(
            name='portprofile',
            options={'verbose_name': 'port profile', 'verbose_name_plural': 'port profiles'},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['building__name'], 'verbose_name': 'room', 'verbose_name_plural': 'rooms'},
        ),
        migrations.AlterModelOptions(
            name='stack',
            options={'verbose_name': 'switches stack', 'verbose_name_plural': 'switches stacks'},
        ),
        migrations.AlterModelOptions(
            name='switch',
            options={'verbose_name': 'switch', 'verbose_name_plural': 'switches'},
        ),
        migrations.AlterModelOptions(
            name='switchbay',
            options={'verbose_name': 'switch bay', 'verbose_name_plural': 'switch bays'},
        ),
        migrations.AlterField(
            model_name='port',
            name='related',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_port', to='topologie.Port'),
        ),
    ]
