# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-02 10:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("topologie", "0024_auto_20170818_1021"),
        ("topologie", "0024_auto_20170826_1800"),
    ]

    operations = []
