# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-05 12:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("topologie", "0026_auto_20170902_1245")]

    operations = [
        migrations.AlterModelOptions(name="room", options={"ordering": ["name"]}),
        migrations.AlterField(
            model_name="port",
            name="radius",
            field=models.CharField(
                choices=[
                    ("NO", "NO"),
                    ("STRICT", "STRICT"),
                    ("BLOQ", "BLOQ"),
                    ("COMMON", "COMMON"),
                ],
                default="NO",
                max_length=32,
            ),
        ),
    ]
