# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-15 18:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topologie', '0030_auto_20171004_0235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='port',
            name='port',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='stack',
            name='member_id_max',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='stack',
            name='member_id_min',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='switch',
            name='number',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='switch',
            name='stack_member_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
