# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-26 01:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("topologie", "0031_auto_20171015_2033")]

    operations = [
        migrations.CreateModel(
            name="ConstructorSwitch",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="ModelSwitch",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reference", models.CharField(max_length=255)),
                (
                    "constructor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="topologie.ConstructorSwitch",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="switch",
            name="model",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="topologie.ModelSwitch",
            ),
        ),
    ]
