# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-12-31 16:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("topologie", "0032_auto_20171026_0338")]

    operations = [
        migrations.AlterModelOptions(
            name="constructorswitch",
            options={
                "permissions": (
                    ("view_constructorswitch", "Peut voir un objet constructorswitch"),
                )
            },
        ),
        migrations.AlterModelOptions(
            name="modelswitch",
            options={
                "permissions": (("view_modelswitch", "Peut voir un objet modelswitch"),)
            },
        ),
        migrations.AlterModelOptions(
            name="port",
            options={"permissions": (("view_port", "Peut voir un objet port"),)},
        ),
        migrations.AlterModelOptions(
            name="room",
            options={
                "ordering": ["name"],
                "permissions": (("view_room", "Peut voir un objet chambre"),),
            },
        ),
        migrations.AlterModelOptions(
            name="stack",
            options={"permissions": (("view_stack", "Peut voir un objet stack"),)},
        ),
        migrations.AlterModelOptions(
            name="switch",
            options={"permissions": (("view_switch", "Peut voir un objet switch"),)},
        ),
    ]
