# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-03-23 23:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("topologie", "0034_borne")]

    operations = [
        migrations.AlterField(
            model_name="borne",
            name="location",
            field=models.CharField(
                blank=True,
                help_text="Détails sur la localisation de l'AP",
                max_length=255,
                null=True,
            ),
        )
    ]
