# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-03-25 00:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0076_auto_20180130_1623'),
        ('topologie', '0036_transferborne'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewSwitch',
            fields=[
                ('interface_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='machines.Interface')),
                ('location', models.CharField(max_length=255)),
                ('number', models.PositiveIntegerField()),
                ('stack_member_id', models.PositiveIntegerField(blank=True, null=True)),
                ('model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='topologie.ModelSwitch')),
                ('stack', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='topologie.Stack')),
            ],
            bases=('machines.interface',),
        ),
        migrations.AlterUniqueTogether(
            name='newswitch',
            unique_together=set([('stack', 'stack_member_id')]),
        ),
    ]
