# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-12-31 19:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topologie', '0040_transferports'),
    ]

    operations = [
    migrations.RemoveField(
        model_name='port',
        name='switch',
    ),
    migrations.RenameField('Port', 'new_switch', 'switch')
    ]
