# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-03-23 01:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("topologie", "0046_auto_20180326_0129")]

    operations = [
        migrations.CreateModel(
            name="NewAccessPoint",
            fields=[
                (
                    "machine_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="machines.Machine",
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        help_text="Détails sur la localisation de l'AP",
                        max_length=255,
                        null=True,
                        blank=True,
                    ),
                ),
            ],
            bases=("machines.machine",),
        )
    ]
