# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-04-08 01:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('topologie', '0056_building_switchbay'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='switchbay',
            name='members',
        ),
        migrations.AddField(
            model_name='switch',
            name='switchbay',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='topologie.SwitchBay'),
        ),
    ]
