# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-05-21 19:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("machines", "0081_auto_20180521_1413"),
        ("topologie", "0059_auto_20180415_2249"),
    ]

    operations = [
        migrations.CreateModel(
            name="Server",
            fields=[],
            options={"proxy": True},
            bases=("machines.machine",),
        )
    ]
