# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-05-26 22:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import re2o.mixins


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0081_auto_20180521_1413'),
        ('topologie', '0060_server'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_default', models.BooleanField()),
                ('hotspot_default', models.BooleanField()),
                ('uplink_default', models.BooleanField()),
                ('orga_machine_default', models.BooleanField()),
                ('radius_type', models.CharField(choices=[('NO', 'NO'), ('802.1X', '802.1X'), ('MAC-radius', 'MAC-radius')], max_length=32)),
                ('radius_mode', models.CharField(choices=[('STRICT', 'STRICT'), ('COMMON', 'COMMON')], max_length=32)),
                ('vlan_tagged', models.ManyToManyField(related_name='vlan_tagged', to='machines.Vlan')),
                ('vlan_untagged', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vlan_untagged', to='machines.Vlan')),
            ],
            options={
                'permissions': (('view_port_profile', 'Can view a port profile object'),),
            },
            bases=(re2o.mixins.AclMixin, models.Model),
        ),
    ]
