# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-06-09 16:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topologie', '0062_auto_20180609_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portprofile',
            name='vlan_tagged',
            field=models.ManyToManyField(blank=True, related_name='vlan_tagged', to='machines.Vlan', verbose_name='VLAN(s) tagged'),
        ),
    ]
