# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-09-20 16:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topologie', '0063_auto_20180919_2225'),
    ]

    operations = [
        migrations.AddField(
            model_name='switch',
            name='automatic_provision',
            field=models.BooleanField(default=False, help_text='Provision automatique de ce switch'),
        ),
    ]
