# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-06-30 15:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topologie', '0064_createprofil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='port',
            name='radius',
        ),
        migrations.RemoveField(
            model_name='port',
            name='vlan_force',
        ),
    ]
