# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-10-11 17:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("topologie", "0065_auto_20180927_1836")]

    operations = [
        migrations.AddField(
            model_name="modelswitch",
            name="commercial_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        )
    ]
