# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-06-30 16:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topologie', '0065_auto_20180630_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='port',
            name='state',
            field=models.BooleanField(default=True, help_text='Etat du port Actif', verbose_name='Etat du port Actif'),
        ),
        migrations.AlterField(
            model_name='portprofile',
            name='profil_default',
            field=models.CharField(blank=True, choices=[('room', 'room'), ('accespoint', 'accesspoint'), ('uplink', 'uplink'), ('asso_machine', 'asso_machine'), ('nothing', 'nothing')], max_length=32, null=True, unique=True, verbose_name='profil default'),
        ),
    ]
