# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-06-30 22:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topologie', '0066_auto_20180630_1855'),
    ]

    operations = [
        migrations.RenameField(
            model_name='port',
            old_name='custom_profil',
            new_name='custom_profile',
        ),
        migrations.AlterField(
            model_name='port',
            name='state',
            field=models.BooleanField(default=True, help_text='Port state Active', verbose_name='Port State Active'),
        ),
        migrations.AlterField(
            model_name='portprofile',
            name='arp_protect',
            field=models.BooleanField(default=False, help_text='Check if ip is dhcp assigned', verbose_name='Arp protect'),
        ),
        migrations.AlterField(
            model_name='portprofile',
            name='dhcp_snooping',
            field=models.BooleanField(default=False, help_text='Protect against rogue dhcp', verbose_name='Dhcp snooping'),
        ),
        migrations.AlterField(
            model_name='portprofile',
            name='dhcpv6_snooping',
            field=models.BooleanField(default=False, help_text='Protect against rogue dhcpv6', verbose_name='Dhcpv6 snooping'),
        ),
        migrations.AlterField(
            model_name='portprofile',
            name='flow_control',
            field=models.BooleanField(default=False, help_text='Flow control', verbose_name='Flow control'),
        ),
        migrations.AlterField(
            model_name='portprofile',
            name='loop_protect',
            field=models.BooleanField(default=False, help_text='Protect again loop', verbose_name='Loop Protect'),
        ),
        migrations.AlterField(
            model_name='portprofile',
            name='mac_limit',
            field=models.IntegerField(blank=True, help_text='Limit of mac-address on this port', null=True, verbose_name='Mac limit'),
        ),
        migrations.AlterField(
            model_name='portprofile',
            name='ra_guard',
            field=models.BooleanField(default=False, help_text='Protect against rogue ra', verbose_name='Ra guard'),
        ),
        migrations.AlterField(
            model_name='portprofile',
            name='radius_mode',
            field=models.CharField(choices=[('STRICT', 'STRICT'), ('COMMON', 'COMMON')], default='COMMON', help_text='In case of mac-auth : mode common or strict on this port', max_length=32, verbose_name='RADIUS mode'),
        ),
        migrations.AlterField(
            model_name='portprofile',
            name='radius_type',
            field=models.CharField(choices=[('NO', 'NO'), ('802.1X', '802.1X'), ('MAC-radius', 'MAC-radius')], help_text='Type of radius auth : inactive, mac-address or 802.1X', max_length=32, verbose_name='RADIUS type'),
        ),
        migrations.AlterField(
            model_name='portprofile',
            name='speed',
            field=models.CharField(choices=[('10-half', '10-half'), ('100-half', '100-half'), ('10-full', '10-full'), ('100-full', '100-full'), ('1000-full', '1000-full'), ('auto', 'auto'), ('auto-10', 'auto-10'), ('auto-100', 'auto-100')], default='auto', help_text='Port speed limit', max_length=32, verbose_name='Speed'),
        ),
    ]
