# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-07-08 19:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topologie', '0067_auto_20180701_0016'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelswitch',
            name='firmware',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
