# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-04-19 14:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topologie', '0073_auto_20191120_0159'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portprofile',
            options={'permissions': (('view_portprofile', 'Can view a port profile object'),), 'verbose_name': 'port profile', 'verbose_name_plural': 'port profiles'},
        ),
    ]
