# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-11-20 00:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='preferences',
            options={'verbose_name': 'tickets preferences'},
        ),
        migrations.AlterModelOptions(
            name='ticket',
            options={'permissions': (('view_tickets', 'Can view a ticket object'),), 'verbose_name': 'ticket', 'verbose_name_plural': 'tickets'},
        ),
        migrations.AlterField(
            model_name='preferences',
            name='mail_language',
            field=models.IntegerField(choices=[(0, 'French'), (1, 'English')], default=0),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='publish_address',
            field=models.EmailField(help_text='Email address to publish the new tickets (leave empty for no publication).', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='description',
            field=models.TextField(help_text='Description of the ticket.', max_length=3000),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='email',
            field=models.EmailField(help_text='An email address to get back to you.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='title',
            field=models.CharField(help_text='Title of the ticket.', max_length=255),
        ),
    ]
