# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-04-22 16:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_auto_20191120_0159'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Preferences',
            new_name='TicketOption',
        ),
        migrations.AlterModelOptions(
            name='ticketoption',
            options={'permissions': (('view_ticketoption', 'Can view tickets options'),), 'verbose_name': 'tickets options'},
        ),
    ]
