# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-04-23 01:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_auto_20200423_0202'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='language',
            field=models.CharField(default='en', help_text='Language of the ticket.', max_length=16),
        ),
    ]
